// src/components/marketplace/mockData.ts
import { PhotoCardListItemProps } from '@/src/components/common/photoCard/organisms/photoCardListItem/photoCardListItem.types';

export const mockPhotoCards: PhotoCardListItemProps[] = [
  {
    variant: 'amount',
    fontWeight: 'bold',
    cardName: '포토카드 A',
    grade: 'legendary',
    genre: 'travel',
    nickname: '여행광1',
    price: 2000,
    image: '/images/sample-image-1.webp',
    totalAmount: 50,
    soldAmount: 20,
    headerWeight: 'bold',
  },
  {
    variant: 'amount',
    fontWeight: 'bold',
    cardName: '포토카드 B',
    grade: 'common',
    genre: 'landscape',
    nickname: '풍경작가1',
    price: 1500,
    image: '/images/sample-image-2.webp',
    totalAmount: 50,
    soldAmount: 10,
    headerWeight: 'bold',
  },
  {
    variant: 'amount',
    fontWeight: 'bold',
    cardName: '포토카드 C',
    grade: 'rare',
    genre: 'portrait',
    nickname: '초상화화가1',
    price: 1800,
    image: '/images/sample-image-3.webp',
    totalAmount: 50,
    soldAmount: 30,
    headerWeight: 'bold',
  },
  {
    variant: 'amount',
    fontWeight: 'bold',
    cardName: '포토카드 D',
    grade: 'superRare',
    genre: 'stillLife',
    nickname: '정물화작가1',
    price: 2500,
    image: '/images/sample-image-1.webp',
    totalAmount: 50,
    soldAmount: 5,
    headerWeight: 'bold',
  },
  {
    variant: 'amount',
    fontWeight: 'bold',
    cardName: '포토카드 E',
    grade: 'common',
    genre: 'landscape',
    nickname: '풍경작가2',
    price: 1200,
    image: '/images/sample-image-2.webp',
    totalAmount: 50,
    soldAmount: 25,
    headerWeight: 'bold',
  },
  {
    variant: 'amount',
    fontWeight: 'bold',
    cardName: '포토카드 F',
    grade: 'legendary',
    genre: 'portrait',
    nickname: '초상화화가2',
    price: 2200,
    image: '/images/sample-image-3.webp',
    totalAmount: 50,
    soldAmount: 15,
    headerWeight: 'bold',
  },
  {
    variant: 'amount',
    fontWeight: 'bold',
    cardName: '포토카드 G',
    grade: 'rare',
    genre: 'travel',
    nickname: '여행광2',
    price: 1900,
    image: '/images/sample-image-1.webp',
    totalAmount: 50,
    soldAmount: 12,
    headerWeight: 'bold',
  },
  {
    variant: 'amount',
    fontWeight: 'bold',
    cardName: '포토카드 H',
    grade: 'superRare',
    genre: 'stillLife',
    nickname: '정물화작가2',
    price: 2600,
    image: '/images/sample-image-2.webp',
    totalAmount: 50,
    soldAmount: 8,
    headerWeight: 'bold',
  },
  {
    variant: 'amount',
    fontWeight: 'bold',
    cardName: '포토카드 I',
    grade: 'legendary',
    genre: 'landscape',
    nickname: '풍경작가3',
    price: 2100,
    image: '/images/sample-image-3.webp',
    totalAmount: 50,
    soldAmount: 18,
    headerWeight: 'bold',
  },
  {
    variant: 'amount',
    fontWeight: 'bold',
    cardName: '포토카드 J',
    grade: 'common',
    genre: 'portrait',
    nickname: '초상화화가3',
    price: 1600,
    image: '/images/sample-image-1.webp',
    totalAmount: 50,
    soldAmount: 22,
    headerWeight: 'bold',
  },
  {
    variant: 'amount',
    fontWeight: 'bold',
    cardName: '포토카드 K',
    grade: 'rare',
    genre: 'stillLife',
    nickname: '정물화작가3',
    price: 2400,
    image: '/images/sample-image-2.webp',
    totalAmount: 50,
    soldAmount: 14,
    headerWeight: 'bold',
  },
  {
    variant: 'amount',
    fontWeight: 'bold',
    cardName: '포토카드 L',
    grade: 'superRare',
    genre: 'travel',
    nickname: '여행광3',
    price: 3000,
    image: '/images/sample-image-3.webp',
    totalAmount: 50,
    soldAmount: 3,
    headerWeight: 'bold',
  },
  {
    variant: 'amount',
    fontWeight: 'bold',
    cardName: '포토카드 M',
    grade: 'legendary',
    genre: 'landscape',
    nickname: '풍경작가4',
    price: 2200,
    image: '/images/sample-image-1.webp',
    totalAmount: 50,
    soldAmount: 20,
    headerWeight: 'bold',
  },
  {
    variant: 'amount',
    fontWeight: 'bold',
    cardName: '포토카드 N',
    grade: 'common',
    genre: 'stillLife',
    nickname: '정물화작가4',
    price: 1300,
    image: '/images/sample-image-2.webp',
    totalAmount: 50,
    soldAmount: 18,
    headerWeight: 'bold',
  },
  {
    variant: 'amount',
    fontWeight: 'bold',
    cardName: '포토카드 O',
    grade: 'rare',
    genre: 'travel',
    nickname: '여행광4',
    price: 1900,
    image: '/images/sample-image-3.webp',
    totalAmount: 50,
    soldAmount: 9,
    headerWeight: 'bold',
  },
  {
    variant: 'amount',
    fontWeight: 'bold',
    cardName: '포토카드 P',
    grade: 'superRare',
    genre: 'landscape',
    nickname: '풍경작가5',
    price: 2800,
    image: '/images/sample-image-1.webp',
    totalAmount: 50,
    soldAmount: 6,
    headerWeight: 'bold',
  },
  {
    variant: 'amount',
    fontWeight: 'bold',
    cardName: '포토카드 Q',
    grade: 'legendary',
    genre: 'stillLife',
    nickname: '정물화작가5',
    price: 2300,
    image: '/images/sample-image-2.webp',
    totalAmount: 50,
    soldAmount: 12,
    headerWeight: 'bold',
  },
  {
    variant: 'amount',
    fontWeight: 'bold',
    cardName: '포토카드 R',
    grade: 'common',
    genre: 'portrait',
    nickname: '초상화화가4',
    price: 1700,
    image: '/images/sample-image-3.webp',
    totalAmount: 50,
    soldAmount: 15,
    headerWeight: 'bold',
  },
  {
    variant: 'amount',
    fontWeight: 'bold',
    cardName: '포토카드 S',
    grade: 'rare',
    genre: 'landscape',
    nickname: '풍경작가6',
    price: 2000,
    image: '/images/sample-image-1.webp',
    totalAmount: 50,
    soldAmount: 8,
    headerWeight: 'bold',
  },
  {
    variant: 'amount',
    fontWeight: 'bold',
    cardName: '포토카드 T',
    grade: 'superRare',
    genre: 'stillLife',
    nickname: '정물화작가6',
    price: 3000,
    image: '/images/sample-image-2.webp',
    totalAmount: 50,
    soldAmount: 4,
    headerWeight: 'bold',
  },
  {
    variant: 'amount',
    fontWeight: 'bold',
    cardName: '포토카드 U',
    grade: 'legendary',
    genre: 'travel',
    nickname: '여행광5',
    price: 2100,
    image: '/images/sample-image-3.webp',
    totalAmount: 50,
    soldAmount: 19,
    headerWeight: 'bold',
  },
  {
    variant: 'amount',
    fontWeight: 'bold',
    cardName: '포토카드 V',
    grade: 'common',
    genre: 'portrait',
    nickname: '초상화화가5',
    price: 1600,
    image: '/images/sample-image-1.webp',
    totalAmount: 50,
    soldAmount: 22,
    headerWeight: 'bold',
  },
];
